.common:
  timeout: 1 hour
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  cache:
    key: $CI_JOB_NAME
    paths:
      - cache.tar.zstd
  tags:
    - local
  before_script:
    - export THREADS=$(nproc)
    - export CABAL_JOBS=$(nproc)
    - tar -xf cache.tar.zstd -C / || true
    - .ci/setup.sh
    - export
  after_script:
    - tar -cf - $(ls -d /root/.cabal /root/.stack /nix || true) | zstd -T0 -3 > cache.tar.zstd

.common-806:
  extends: .common
  image: docker.pkg.github.com/clash-lang/clash-protocols/protocols-focal-ghc-cabal-stack-8.6.5:2020-12-07
  variables:
    GHC_VERSION: "8.6.5"
    CABAL_VERSION: "3.2.0.0"

.common-810:
  extends: .common
  image: docker.pkg.github.com/clash-lang/clash-protocols/protocols-focal-ghc-cabal-stack-8.10.2:2020-12-07
  variables:
    GHC_VERSION: "8.10.2"
    CABAL_VERSION: "3.2.0.0"

# Haddock is broken on 865.
haddock:
  extends: .common-810
  artifacts:
    paths:
      - docs/*
    expire_in: 1 month
  script:
    - .ci/build_docs.sh

# Circuit-notation is broken on 810.
# https://github.com/cchalmers/circuit-notation/pull/8#issuecomment-739844352
cabal-8.6.5:
  extends: .common-806
  script:
    - .ci/test_cabal.sh

stack:
  extends: .common-806
  script:
    - .ci/test_stack.sh
