resolver: lts-21.25 # ghc-9.4.8

packages:
  - clash-protocols-base
  - clash-protocols

extra-deps:
- git: https://github.com/cchalmers/circuit-notation.git
  commit: 564769c52aa05b90f81bbc898b7af7087d96613d
- clash-prelude-1.8.1
- clash-prelude-hedgehog-1.8.1
