resolver: lts-18.26 # ghc-8.10.7

packages:
  - .

extra-deps:
- git: https://github.com/martijnbastiaan/haskell-hedgehog.git
  commit: 41e87d110d3b2b7b522d29d7c0500672f2640dcc
  subdirs:
    - hedgehog
- git: https://github.com/cchalmers/circuit-notation.git
  commit: 2574640364eef12222517af059b9e4a7e6b503a7
- tasty-hedgehog-1.2.0.0
- clash-prelude-1.6.3
- clash-prelude-hedgehog-1.6.3
